In [1]:
import duckdb

Seleciona o banco de dados

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

Vamos ver como esta o banco de dados da camada silver

In [3]:
df =con.execute("SELECT * FROM produtos").fetchdf()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10002    MARTELO         BT50            100    1500.0
1  10005    MACHADO         BT50            100     100.0
2  10001   PARAFUSO         BT10            100     100.0
3  10004      SERRA         BT50            100     200.0
4  10003      PREGO         BT10            100      60.0

Agora vamos criar uma dimensão na camada gold, vamos modificar o df2 e remover as colunas id_categoria e id_fornecedor

In [4]:
df2 =df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)

      id nm_produto  vl_preco
0  10002    MARTELO    1500.0
1  10005    MACHADO     100.0
2  10001   PARAFUSO     100.0
3  10004      SERRA     200.0
4  10003      PREGO      60.0

Agora vamos cria a nossa tabela na camada gold para poder fazer a insersão dos dados

repare que inserimos os nomes das tabelas em maiusculo, podemos alterar utilizando a função ALTER ou excluir toda a tabela com a função DROP, como boas praticas utilize sempre nomes em minusculo

In [ ]:
con.execute("""
    DROP TABLE IF EXISTS dim_produtos
""")

In [10]:
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produtos (
            id_produto BIGINT,
            nm_produto TEXT,
            vl_produto FLOAT
            )
         
 """)

FAMOS FAZER UMA CONSULTA NA dim_produtos

In [11]:
df_dim = con.execute("SELECT * FROM dim_produtos").fetchdf()
df_dim.head(10)

Empty DataFrame
Columns: [id_produto, nm_produto, vl_produto]
Index: []

Agora vamos fazer a insersão dos dados na tabela dim_produtos como os dados vindo do dataframe df2

In [13]:
con.execute("INSERT INTO dim_produtos SELECT * FROM df2")
con.execute("SELECT * FROM dim_produtos").fetchdf().head(10)

   id_produto nm_produto  vl_produto
0       10002    MARTELO      1500.0
1       10005    MACHADO       100.0
2       10001   PARAFUSO       100.0
3       10004      SERRA       200.0
4       10003      PREGO        60.0
5       10002    MARTELO      1500.0
6       10005    MACHADO       100.0
7       10001   PARAFUSO       100.0
8       10004      SERRA       200.0
9       10003      PREGO        60.0

Agora precisa fechar a conexão

In [14]:
con.close()

agora vamos commitar os arquivos para o nosso repositorio do github, abre o terminal git bash do vscode